/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projects;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class JProduct_info extends javax.swing.JFrame {

    private boolean res;

    /**
     * Creates new form JProduct_info
     */
    public JProduct_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jIProd = new javax.swing.JButton();
        JDProd = new javax.swing.JButton();
        JUProd = new javax.swing.JButton();
        JPProd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Product_info_group = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Dpid = new javax.swing.JTextField();
        Ddeleted = new javax.swing.JLabel();
        Dnotdeleted = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Upid = new javax.swing.JTextField();
        Ulist = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        Uvalue = new javax.swing.JLabel();
        UPvalue = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        Uupdated = new javax.swing.JLabel();
        Unotupdated = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Ppid = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        PPname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        PPprice = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        PPoffer = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        PCname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        PCdetails = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        PDname = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        PDdetails = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        PDcontactno = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        PDemail = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Pgstno = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        PPpaydetails = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Ponstock = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        JPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JLPid = new javax.swing.JLabel();
        JPid = new javax.swing.JTextField();
        JLPname = new javax.swing.JLabel();
        JPname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JPprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JPoffer = new javax.swing.JTextField();
        JFCname = new javax.swing.JLabel();
        JCname = new javax.swing.JTextField();
        JFCdetails = new javax.swing.JLabel();
        JCdetails = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JDname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JDdetails = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JDcontact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JDemail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Jgst = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JPPdetails = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        JNstock = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Jinserted = new javax.swing.JLabel();
        Jnotinserted = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jIProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jIProd.setText("Insert Product Data");
        jIProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIProdActionPerformed(evt);
            }
        });

        JDProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JDProd.setText("Delete Product Data");
        JDProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDProdActionPerformed(evt);
            }
        });

        JUProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JUProd.setText("Update Product Data");
        JUProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUProdActionPerformed(evt);
            }
        });

        JPProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JPProd.setText("Print Product Data");
        JPProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPProdActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Back to Main Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JDProd)
                            .addComponent(jIProd)
                            .addComponent(JUProd)
                            .addComponent(JPProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jIProd)
                .addGap(37, 37, 37)
                .addComponent(JDProd)
                .addGap(37, 37, 37)
                .addComponent(JUProd)
                .addGap(34, 34, 34)
                .addComponent(JPProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(91, 91, 91))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 600));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Delete Product Data");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Enter the Product Id");

        Dpid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Ddeleted.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ddeleted.setForeground(new java.awt.Color(102, 255, 0));

        Dnotdeleted.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Dnotdeleted.setForeground(new java.awt.Color(255, 0, 0));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(Dpid, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(Ddeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(Dnotdeleted)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(336, 336, 336))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(84, 84, 84)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dpid))
                .addGap(103, 103, 103)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dnotdeleted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ddeleted))
                .addGap(133, 133, 133)
                .addComponent(jButton5)
                .addGap(195, 195, 195))
        );

        Product_info_group.addTab("tab2", jPanel4);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Update Product Data");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Enter the Product Id");

        Upid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Upid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpidActionPerformed(evt);
            }
        });

        Ulist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select --", "Product Name", "Product Price", "Product Offer", "Company Name", "Company Details", "Dealer Name", "Dealer Details", "Dealer Contact No", "Dealer Email", "GST no", "Product Payment details", "no of Stock" }));
        Ulist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlistActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Select Which Column to Update");

        Uvalue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Uvalue.setText("Enter the Value");

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Uupdated.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Uupdated.setForeground(new java.awt.Color(51, 255, 0));

        Unotupdated.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Unotupdated.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Unotupdated)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(jLabel28))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(107, 107, 107)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Uupdated)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Uvalue)
                                            .addComponent(jLabel27)))))
                            .addGap(59, 59, 59)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Ulist, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UPvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Upid, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(281, 281, 281))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ulist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(Upid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Uvalue)
                            .addComponent(UPvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Unotupdated)
                            .addComponent(Uupdated))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(161, 161, 161))
        );

        Product_info_group.addTab("tab3", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Print Product Data");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Enter Product Id");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));
        jPanel5.add(Ppid, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 40, 110, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Product Name");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        PPname.setEditable(false);
        jPanel5.add(PPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 270, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Product Price");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        PPprice.setEditable(false);
        PPprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPpriceActionPerformed(evt);
            }
        });
        jPanel5.add(PPprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 270, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Product offer");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        PPoffer.setEditable(false);
        jPanel5.add(PPoffer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 270, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Company Name");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        PCname.setEditable(false);
        jPanel5.add(PCname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 270, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Company Deatails");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        PCdetails.setEditable(false);
        jPanel5.add(PCdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 270, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Dealer Name");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        PDname.setEditable(false);
        PDname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PDname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDnameActionPerformed(evt);
            }
        });
        jPanel5.add(PDname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 270, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Dealer Deatails");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        PDdetails.setEditable(false);
        jPanel5.add(PDdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 270, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Dealer Conatact No");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        PDcontactno.setEditable(false);
        jPanel5.add(PDcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 270, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Dealer Email");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        PDemail.setEditable(false);
        PDemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDemailActionPerformed(evt);
            }
        });
        jPanel5.add(PDemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 270, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Gst No");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        Pgstno.setEditable(false);
        jPanel5.add(Pgstno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 270, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Product Payment Details");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        PPpaydetails.setEditable(false);
        jPanel5.add(PPpaydetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 270, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("No of Stock");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        Ponstock.setEditable(false);
        jPanel5.add(Ponstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 80, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Get Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        Product_info_group.addTab("tab4", jPanel5);

        JPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Insert Product Data");

        JLPid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLPid.setText("Product Id");

        JLPname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLPname.setText("Product Name");

        JPname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Product Price");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Product Offer");

        JFCname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JFCname.setText("Company Name");

        JFCdetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JFCdetails.setText("Company Details");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Dealer Name");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Dealer Details");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Dealer Conatct No");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Dealer Email");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Product Gst No");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Product Payment Details");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("No of Stock ");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Jinserted.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Jinserted.setForeground(new java.awt.Color(0, 255, 0));

        Jnotinserted.setBackground(new java.awt.Color(255, 255, 255));
        Jnotinserted.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Jnotinserted.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel2))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLPname)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(JFCname)
                            .addComponent(JFCdetails)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(JLPid, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCname)
                            .addComponent(JCdetails)
                            .addComponent(JDname)
                            .addComponent(JDdetails)
                            .addComponent(JDcontact)
                            .addComponent(JDemail)
                            .addComponent(JPPdetails)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(JPname)
                                        .addComponent(JPprice)
                                        .addComponent(JPoffer, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                                    .addComponent(Jgst, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JPid, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JNstock, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 50, Short.MAX_VALUE)))))
                .addGap(231, 231, 231))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Jinserted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jnotinserted)
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(323, 323, 323))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLPid)
                    .addComponent(JPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLPname)
                    .addComponent(JPname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JPprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JPoffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JFCname)
                    .addComponent(JCname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JFCdetails)
                    .addComponent(JCdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JDname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JDdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(JDcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JDemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Jgst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(JPPdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(JNstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jinserted)
                    .addComponent(Jnotinserted))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        Product_info_group.addTab("tab1", JPanel1);

        getContentPane().add(Product_info_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -30, 770, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JDProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDProdActionPerformed
        Product_info_group.setSelectedIndex(0);
    }//GEN-LAST:event_JDProdActionPerformed

    private void jIProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIProdActionPerformed
        Product_info_group.setSelectedIndex(3);
    }//GEN-LAST:event_jIProdActionPerformed

    private void JUProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUProdActionPerformed
        Product_info_group.setSelectedIndex(1);
    }//GEN-LAST:event_JUProdActionPerformed

    private void JPProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPProdActionPerformed
        Product_info_group.setSelectedIndex(2);
    }//GEN-LAST:event_JPProdActionPerformed

    private void JPnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int pid,pprice,poffer,pgstno,pstockno;
        long dcontactno;
        String pname,cname,cdetails,dname,ddetails,demail,ppaydetails;
        pid=Integer.parseInt(JPid.getText());
        pname=JPname.getText();
        pprice=Integer.parseInt(JPprice.getText());
        poffer=Integer.parseInt(JPoffer.getText());
        cname=JCname.getText();
        cdetails=JCdetails.getText();
        dname=JDname.getText();
        ddetails=JDdetails.getText();
        dcontactno=Long.parseLong(JDcontact.getText());
        demail=JDemail.getText();
        pgstno=Integer.parseInt(Jgst.getText());
        ppaydetails=JPPdetails.getText();
        pstockno=Integer.parseInt(JNstock.getText());
        try {
            boolean out=Product_info.insertProductData(pid,pprice,poffer,dcontactno,pgstno,pstockno,pname, cname, cdetails, dname, ddetails, demail, ppaydetails);
            if(out==true){Jinserted.setText("Record Inserted");}
            else{Jnotinserted.setText("Record not Inserted");}
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PPpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PPpriceActionPerformed

    private void PDemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDemailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int pid1=Integer.parseInt(Ppid.getText());
        try{ Product_info.printProductData(pid1);}
        catch(Exception e){e.printStackTrace();}
        PPname.setText(Product_info.pdname);
        PPprice.setText(Product_info.ppprice+"");
        PPoffer.setText(Product_info.ppoffer+"");
        PCname.setText(Product_info.pcname);
        PCdetails.setText(Product_info.pcdetails);
        PDname.setText(Product_info.pdname);
        PDdetails.setText(Product_info.pddetails);
        PDcontactno.setText(Product_info.pdcontactno+"");
        PDemail.setText(Product_info.pdemail);
        Pgstno.setText(Product_info.ppgstno+"");
        PPpaydetails.setText(Product_info.pppaydetails);
        Ponstock.setText(Product_info.ppstockno+"");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PDnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDnameActionPerformed

    private void UpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpidActionPerformed
      static String plist;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int pid=Integer.parseInt(Upid.getText());
        String pvalue=UPvalue.getText();
        int ind=Ulist.getSelectedIndex();
        try{res=Product_info.updateData(ind, pid, pvalue);
        }
        catch(Exception e){}
        System.out.println(res);
        if(res){Uupdated.setText(plist+" Data Updated");}
        else{Unotupdated.setText("Data Not Updated");}
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void UlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlistActionPerformed
        plist = (String) Ulist.getSelectedItem();
        Uvalue.setText("Enter the "+plist+" Column Value");
    }//GEN-LAST:event_UlistActionPerformed
    static boolean Dout;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int pid1=Integer.parseInt(Dpid.getText());
        try{Dout=Product_info.deleteData(pid1);}
        catch(Exception e){e.printStackTrace();}
        if(Dout){Ddeleted.setText("Data Deleted");Dnotdeleted.setText("");}
        else{Dnotdeleted.setText("Data Not Deleted");Ddeleted.setText("");}
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptions jp=new JOptions();
        jp.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JProduct_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JProduct_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JProduct_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JProduct_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JProduct_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ddeleted;
    private javax.swing.JLabel Dnotdeleted;
    private javax.swing.JTextField Dpid;
    private javax.swing.JTextField JCdetails;
    private javax.swing.JTextField JCname;
    private javax.swing.JButton JDProd;
    private javax.swing.JTextField JDcontact;
    private javax.swing.JTextField JDdetails;
    private javax.swing.JTextField JDemail;
    private javax.swing.JTextField JDname;
    private javax.swing.JLabel JFCdetails;
    private javax.swing.JLabel JFCname;
    private javax.swing.JLabel JLPid;
    private javax.swing.JLabel JLPname;
    private javax.swing.JTextField JNstock;
    private javax.swing.JTextField JPPdetails;
    private javax.swing.JButton JPProd;
    private javax.swing.JPanel JPanel1;
    private javax.swing.JTextField JPid;
    private javax.swing.JTextField JPname;
    private javax.swing.JTextField JPoffer;
    private javax.swing.JTextField JPprice;
    private javax.swing.JButton JUProd;
    private javax.swing.JTextField Jgst;
    private javax.swing.JLabel Jinserted;
    private javax.swing.JLabel Jnotinserted;
    private javax.swing.JTextField PCdetails;
    private javax.swing.JTextField PCname;
    private javax.swing.JTextField PDcontactno;
    private javax.swing.JTextField PDdetails;
    private javax.swing.JTextField PDemail;
    private javax.swing.JTextField PDname;
    private javax.swing.JTextField PPname;
    private javax.swing.JTextField PPoffer;
    private javax.swing.JTextField PPpaydetails;
    private javax.swing.JTextField PPprice;
    private javax.swing.JTextField Pgstno;
    private javax.swing.JTextField Ponstock;
    private javax.swing.JTextField Ppid;
    private javax.swing.JTabbedPane Product_info_group;
    private javax.swing.JTextField UPvalue;
    private javax.swing.JComboBox<String> Ulist;
    private javax.swing.JLabel Unotupdated;
    private javax.swing.JTextField Upid;
    private javax.swing.JLabel Uupdated;
    private javax.swing.JLabel Uvalue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jIProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    private void Product_info(int pid1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
